/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Documents
         * @description The document list/dashboard's data source. Filters are all optional
         *     and combine with AND; unfiltered returns the most recent filings first.
         */
        get: operations["list_documents_documents_get"];
        put?: never;
        /**
         * Submit Document
         * @description Accepts a filing tagged with the company + reporting period it covers,
         *     and returns immediately with the new document's id/status — the actual
         *     LangGraph review (extraction, then a real interrupt() pause if anything
         *     needs approval — see app/graph/agent.py) runs in the background so this
         *     request doesn't block on the LLM.
         *
         *     Looks up the company by ticker, creating a bare row (ticker only — name/
         *     CIK get filled in once EDGAR ingestion lands) if this is the first filing
         *     seen for it.
         *
         *     Note: reads the upload as UTF-8 text directly. Filings are typically
         *     plain text or already-extracted text at this stage — HTML/PDF filings
         *     straight from EDGAR would need a text-extraction step first; that's a
         *     TODO for the EDGAR ingestion path, not this one.
         */
        post: operations["submit_document_documents_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documents/{document_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Document */
        get: operations["get_document_documents__document_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reviews/{document_id}/findings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Findings */
        get: operations["list_findings_reviews__document_id__findings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reviews/{document_id}/decision": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Submit Decision
         * @description Resumes a paused review with a human's approve/reject decision. Named
         *     "decision" rather than "approve" since ReviewDecision.decision covers
         *     both outcomes in one body.
         *
         *     Rejects with 409 if the document isn't actually paused — resuming a
         *     thread that was never interrupted (or was already resumed) is a no-op at
         *     best and a race at worst, so this fails loudly instead.
         */
        post: operations["submit_decision_reviews__document_id__decision_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/companies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Companies */
        get: operations["list_companies_companies_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/companies/{ticker}/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Company Metrics
         * @description One company's metric(s) over time — quarter-over-quarter / year-over-year
         *     trend view. Omit metric_name to get every tracked metric, ordered so a
         *     client can group by metric_name itself.
         */
        get: operations["get_company_metrics_companies__ticker__metrics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metrics/compare": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Compare Metric
         * @description Same metric across multiple companies — for peer comparison.
         */
        get: operations["compare_metric_metrics_compare_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_submit_document_documents_post */
        Body_submit_document_documents_post: {
            /** File */
            file: string;
            /**
             * Ticker
             * @description Stock ticker, e.g. AAPL
             */
            ticker: string;
            filing_type: components["schemas"]["FilingType"];
            /** Fiscal Year */
            fiscal_year: number;
            fiscal_period: components["schemas"]["FiscalPeriod"];
            /** Period End Date */
            period_end_date?: string | null;
        };
        /** Company */
        Company: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Ticker */
            ticker: string;
            /** Cik */
            cik?: string | null;
            /** Name */
            name?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** DocumentOut */
        DocumentOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Filename */
            filename: string;
            status: components["schemas"]["ReviewStatus"];
            /** Company Id */
            company_id?: string | null;
            /** Ticker */
            ticker?: string | null;
            /** Company Name */
            company_name?: string | null;
            filing_type?: components["schemas"]["FilingType"] | null;
            /** Fiscal Year */
            fiscal_year?: number | null;
            fiscal_period?: components["schemas"]["FiscalPeriod"] | null;
            /** Period End Date */
            period_end_date?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * FilingType
         * @enum {string}
         */
        FilingType: "10-K" | "10-Q" | "8-K" | "DEF 14A" | "other";
        /** FinancialMetric */
        FinancialMetric: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Document Id
             * Format: uuid
             */
            document_id: string;
            /**
             * Company Id
             * Format: uuid
             */
            company_id: string;
            /** Metric Name */
            metric_name: string;
            /** Value */
            value: number;
            unit: components["schemas"]["MetricUnit"];
            period_type: components["schemas"]["MetricPeriodType"];
            /** Fiscal Year */
            fiscal_year: number;
            fiscal_period: components["schemas"]["FiscalPeriod"];
            /** Period End Date */
            period_end_date?: string | null;
            /** Citation */
            citation?: string | null;
            /** Confidence */
            confidence?: number | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** Finding */
        Finding: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Document Id
             * Format: uuid
             */
            document_id: string;
            /** Company Id */
            company_id?: string | null;
            /** @default other */
            category: components["schemas"]["FindingCategory"];
            /** Field Name */
            field_name: string;
            /** Value */
            value?: string | null;
            /** @default info */
            severity: components["schemas"]["Severity"];
            /** Confidence */
            confidence?: number | null;
            /** Citation */
            citation?: string | null;
            /**
             * Requires Approval
             * @default false
             */
            requires_approval: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * FindingCategory
         * @enum {string}
         */
        FindingCategory: "risk_factor" | "legal_proceeding" | "accounting_policy" | "governance" | "anomaly" | "other";
        /**
         * FiscalPeriod
         * @enum {string}
         */
        FiscalPeriod: "Q1" | "Q2" | "Q3" | "Q4" | "FY";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * MetricPeriodType
         * @enum {string}
         */
        MetricPeriodType: "annual" | "quarterly" | "ttm";
        /**
         * MetricUnit
         * @enum {string}
         */
        MetricUnit: "usd" | "usd_thousands" | "usd_millions" | "percent" | "ratio" | "shares";
        /** ReviewDecision */
        ReviewDecision: {
            /**
             * Decision
             * @enum {string}
             */
            decision: "approve" | "reject";
            /** Reason */
            reason?: string | null;
            /** Reviewer */
            reviewer?: string | null;
        };
        /**
         * ReviewStatus
         * @enum {string}
         */
        ReviewStatus: "processing" | "awaiting_approval" | "complete" | "rejected" | "failed";
        /**
         * Severity
         * @enum {string}
         */
        Severity: "info" | "warning" | "anomaly" | "critical";
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_documents_documents_get: {
        parameters: {
            query?: {
                status?: components["schemas"]["ReviewStatus"] | null;
                ticker?: string | null;
                filing_type?: components["schemas"]["FilingType"] | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_document_documents_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_submit_document_documents_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_document_documents__document_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_findings_reviews__document_id__findings_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Finding"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_decision_reviews__document_id__decision_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReviewDecision"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_companies_companies_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Company"][];
                };
            };
        };
    };
    get_company_metrics_companies__ticker__metrics_get: {
        parameters: {
            query?: {
                metric_name?: string | null;
            };
            header?: never;
            path: {
                ticker: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FinancialMetric"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    compare_metric_metrics_compare_get: {
        parameters: {
            query: {
                metric_name: string;
                /** @description Comma-separated tickers, e.g. AAPL,MSFT */
                tickers: string;
                period_type?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FinancialMetric"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
